language: android
sudo: required
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-26.0.1
                - android-26
                - extra-android-m2repository
                - extra-google-google_play_services
                - extra-google-m2repository
                - addon-google_apis-google-26
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
                - develop
                - 1.0
